(use-package meow
  :ensure t
  :init
  (defun meow-setup ()
    (setq meow-expand-hint-remove-delay 0.3)
    (meow-leader-define-key
     '("1" . meow-digit-argument)
     '("2" . meow-digit-argument)
     '("3" . meow-digit-argument)
     '("4" . meow-digit-argument)
     '("5" . meow-digit-argument)
     '("6" . meow-digit-argument)
     '("7" . meow-digit-argument)
     '("8" . meow-digit-argument)
     '("9" . meow-digit-argument)
     '("0" . meow-digit-argument)
     '("/" . meow-keypad-describe-key))
    (meow-normal-define-key
     ;; digit arguments
     '("0" . meow-expand-0)
     '("1" . meow-expand-1)
     '("2" . meow-expand-2)
     ;; movements and selections
     '("h" . meow-left)
     '("H" . meow-left-expand)
     '("j" . meow-next)
     '("J" . meow-next-expand)
     '("k" . meow-prev)
     '("K" . meow-prev-expand)
     '("l" . meow-right)
     '("L" . meow-right-expand)
     '("e" . meow-next-word)
     '("E" . meow-next-symbol)
     '("b" . meow-back-word)
     '("B" . meow-back-symbol)
     '("w" . meow-mark-word)
     '("W" . meow-mark-symbol)
     '("f" . meow-find)
     '("t" . meow-till)
     '("n" . repeat)
     '("s" . avy-goto-char-2-below)
     '("S" . avy-goto-char-2-above)
     '("x" . meow-line)
     '("X" . meow-goto-line)
     '("v" . meow-visit)
     '("V" . meow-search)
     '("m" . meow-cancel-selection)
     '("M" . meow-block)
     '("z" . meow-reverse)
     '(";" . meow-join)
     ;; editing
     '("i" . meow-insert)
     '("a" . meow-append)
     '("o" . meow-open-below)
     '("O" . meow-open-above)
     '("r" . meow-replace)
     '("d" . meow-kill)
     '("D" . meow-delete)
     '("c" . meow-change)
     '("g" . meow-grab)
     '("G" . meow-swap-grab)
     '("y" . meow-save)
     '("p" . meow-yank) 
     '("P" . meow-yank-pop)
     '("u" . meow-undo)
     '("U" . meow-undo-in-selection)
     ;; other
     '("RET" . ignore)
     '("<escape>" . ignore)
     '("<backspace>" . ignore)
     ))
  :config
  (meow-setup)
  (meow-global-mode))
