# Base16 Catppuccin Frappe - wezterm color config
# Scheme by https://github.com/catppuccin/catppuccin

[colors]
foreground    = "#c6d0f5"
background    = "#303446"
cursor_bg     = "#c6d0f5"
cursor_border = "#c6d0f5"
cursor_fg     = "#303446"
selection_bg  = "#c6d0f5"
selection_fg  = "#303446"

ansi = [
  "#303446",
  "#e78284",
  "#a6d189",
  "#e5c890",
  "#8caaee",
  "#ca9ee6",
  "#81c8be",
  "#c6d0f5"
]

brights = [
  "#51576d",
  "#e78284",
  "#a6d189",
  "#e5c890",
  "#8caaee",
  "#ca9ee6",
  "#81c8be",
  "#babbf1"
]
