import = [ "~/.config/alacritty/catppuccin-macchiato.toml" ]

[font]
size = 16

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "regular"

[cursor.style]
blinking = "On"

[mouse]
hide_when_typing = true

[window.padding]
x = 16
y = 16
