-- vim.o.termguicolors = true
require("plugin_configs.others")
require("plugin_configs.lualine")
require("plugin_configs.tsitter")
require("plugin_configs.nvim-tree")
require("plugin_configs.modicator")
require("plugin_configs.mason")
require("plugin_configs.nvim-cmp")
require("plugin_configs.wilderness")
require("plugin_configs.which-key")
