theme = "base16_transparent"

[editor]
line-number = "relative"
cursorline = true
auto-save = true
completion-trigger-len = 1
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = ["mode", "file-name", "spinner"]
center = ["position", "position-percentage"]
right = [
  "version-control",
  "diagnostics",
  "selections",
  "register",
  "file-encoding",
]
# separator = "|"
mode.normal = "normal"
mode.insert = "insert"
mode.select = "select"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true

[keys.normal]
F1 = ":w"
