[[language]]
name = "python"
language-servers = [ "pylsp", "ruff" ]

[language-server.ruff]
command = "ruff-lsp"

[language.formatter]
command = "black"
args = [ "--line-length", "80", "--quiet", "-" ]
