[palette0]
background = "24273a"
foreground = "cad3f5"
active     = "8aadf4"
inactive   = "a5adcb"
focused    = "939ab7"
unfocused  = "6e738d"
alert      = "ed8796"

[palette1]
accent0 = "a6da95"
accent1 = "8aadf4"
accent2 = "b7bdf8"
accent3 = "8aadf4"
accent4 = "7dc4e4"
accent5 = "91d7e3"
accent6 = "8bd5ca"
accent7 = "a6da95"
