[palette0]
background = "2D353B"
foreground = "D3C6AA"
active     = "859289"
inactive   = "7A8478"
focused    = "9DA9A0"
unfocused  = "859289"
alert      = "E67E80"

[palette1]
accent0 = "A7C080"
accent1 = "83C092"
accent2 = "E69875"
accent3 = "83C092"
accent4 = "E69875"
accent5 = "A7C080"
accent6 = "E69875"
accent7 = "A7C080"
