[palette0]
background = "2e3440"
foreground = "d8dee9"
active     = "434c5e"
inactive   = "3b4252"
focused    = "4c566a"
unfocused  = "3b4252"
alert      = "bf616a"

[palette1]
accent0 = "a3be8c"
accent1 = "81a1c1"
accent2 = "81a1c1"
accent3 = "81a1c1"
accent4 = "d08770"
accent5 = "a3be8c"
accent6 = "5e81ac"
accent7 = "81a1c1"
