[palette0]
background = "232136"
foreground = "e0def4"
active     = "9ccfd8"
inactive   = "6e6a86"
focused    = "56526e"
unfocused  = "2a283e"
alert      = "eb6f92"

[palette1]
accent0 = "ea9a97"
accent1 = "9ccfd8"
accent2 = "9ccfd8"
accent3 = "ea9a97"
accent4 = "9ccfd8"
accent5 = "eb6f92"
accent6 = "ea9a97"
accent7 = "c4a7e7"
