[general]
terminal = "kitty"
groups   = "1234567890qwetyuiop"
layouts  = ["monadtall", "monadwide", "floating"]
wmname   = "qtile"

[keyboard]
layouts           = ["us", "ru"]
displayes_layouts = { us = "us", ru = "ru" }

[keymappings]
mod   = "mod4"
up    = "k"
down  = "j"
right = "l"
left  = "h"

[visuals]
margin        = 4
bar_position  = "bottom"
theme         = "nord"
font          = "JetBrainsMono Nerd Font"
# wallpaper     = "~/wallpapers/ign_chainsaw-man.png"
wallpaper     = "~/wallpapers/street_blues.png"
